### ISSUE TITLE
Not able to use with Hyperleadger Fabric SDK.

### ISSUE THREAD

**Issue by bdzo** [sewenew/redis-protobuf#14]
Hello,

First of all thank you for building such module. :)

But I am having trouble using this module with Hyperleadger Fabric SDK..

Here is error I am getting:

```
1:M 10 Jan 2020 13:59:19.156 # <PB> failed to load ledger/queryresult/kv_query_result.proto                                                                 
error:google/protobuf/timestamp.proto:-1:0:File not found.                                           
error:ledger/queryresult/kv_query_result.proto:11:0:Import "google/protobuf/timestamp.proto" was not found or had errors.                
error:ledger/queryresult/kv_query_result.proto:26:4:"google.protobuf.Timestamp" is not defined.                                                                                              
1:M 10 Jan 2020 13:59:19.156 # Module /usr/lib/redis/modules/libredis-protobuf.so initialization failed. Module not loaded                                                                     
1:M 10 Jan 2020 13:59:19.156 # Can't load module from /usr/lib/redis/modules/libredis-protobuf.so: server aborting          
```                                                                
  And here is my Dockerimage:

_https://github.com/bdzo/fabric-redis-protobuf_

Thanks
Đorđe

**Comment by sewenew** [comment]
Hi @bdzo 

You got this error, because *google/protobuf/timestamp.proto* is not saved under */usr/lib/redis/proto* directory. [This](https://github.com/sewenew/redis-protobuf/issues/13) is a related issue, and I've fixed the problem. However, you still need to copy these standard proto files to */usr/lib/redis/proto* directory.

Also I'll copy these files to *sewenew/redis-protobuf* docker image. When that's done, you can pull the latest image, and your proto file should be loaded successfully. I'll let you know, when I'm done with that.

Regards

**Comment by sewenew** [comment]
Hi @bdzo 

The Dockerfile has been updated, and it will copy [these](https://github.com/sewenew/redis-protobuf/tree/master/docker/google/protobuf) standard proto files to */usr/lib/redis/proto* directory.

You can try the latest image, and I think it should work now. If you still have any problem with this module, feel free to let me know :)

Regards

**Comment by bdzo** [comment]
Hello,

Thanks for fast response!

It works great!

Kind regards
