### ISSUE TITLE
Cannot see redis-keyspace notifications

### ISSUE THREAD

**Issue by maddypj** [sewenew/redis-protobuf#15]
Hi Sewnew,

I am trying to store the entire proto object in redis in binary format using the redis-protobuf. However I am not able to see any redis keyspace notifications on it. Is this due to redis-protobuf storing data in particular way?
Does redis-protobuf interact with redis notifications? 

Regards,

**Comment by sewenew** [comment]
Hi @maddypj 

Yes, by now, redis-protobuf doesn't support key space notification. Because it's based on Redis 4.0.0's module API. This version doesn't have API for key space notification.

I checked the newer version of module API. It seems that since 4.0.9, it has some support for key space notification. I'll take a deep look into it, and add the support for these notification.

Thanks for pointing this feature out!

Regards

**Comment by sewenew** [comment]
Hi @maddypj 

I double checked the API, and found that Redis Module still doesn't support keysspace notification for [native types](https://redis.io/topics/modules-native-types). You can also check [this Redis issue](https://github.com/antirez/redis/issues/6544), which tries to add keyspace notification support for native types.

redis-protobuf uses native types API, so it cannot send any keyspace notification. I'm sorry for that.

I'll keep this issue open, and will fix it when Redis Module API supports this notification feature in the future.

Regards

**Comment by maddypj** [comment]
It seems it is an issue for all redis-modules. Also redis protobuf only supports API version 4.0.0.
Thanks Sewnew for providing all references!
