### ISSUE TITLE
Merging booleans

### ISSUE THREAD

**Issue by maddypj** [sewenew/redis-protobuf#20]
Hello sewnew,

I was trying merging booleans with protobuf. 
If a value is set as "True" and I am trying to merge "False" to it ; I expect the end result to be "False" stored in the redis-object.
Once the value is set to True; it remains True.  The protobuf merge  API also behaves the same way.
Is there any different method of merging?

Obj1 merging with obj2 -> I expect Obj1 already set attributes remain as they are. Obj2 attributes get updated in Obj1.

Regards,
Maddy

**Comment by sewenew** [comment]
Hi @maddypj 

YES, redis-protobuf behaves the same as protobuf API, since it calls the corresponding API to do the job.

> Is there any different method of merging?

AFAIK, there's no built-in way to do that. You have to write this merging logic by yourself.

Also, since protobuf 3, there's no `has_xxx` method for the generated protobuf message, and I think there's no way to distinguish whether an attribute of boolean type has already been set to False or it has never been set (the default value is False). So it might be hard to implement the merging method that you expect.

Regards
